
spring:
  application:
    name: slugjar
  profiles:
    active: dev
server:
  context-path: '/'
  port: 8080

---

# ====================================== L O C A L =====================================================================

spring:
  profiles: dev
database:
  type: nitrite-db
  filePath: "./slugjar.db.no2"
  username: slugjar-user
  password: changeme
jwt:
  secret: thequickbrownfoxjumpedoverthelazydog

---

# ====================================== P R O D U C T I O N ===========================================================

spring:
  profiles: prod
db:
  source: mongo
  mongo:
    host: localhost
    database: slugjar
    login: slugjar
    password: slugjar
    authDb: admin