
spring:
  application:
    name: slugjar
  profiles:
    active: local
server:
  context-path: '/'
  port: 8081

---

# ====================================== L O C A L =====================================================================

spring:
  profiles: local
db:
  source: mongo
  mongo:
    host: localhost
    database: slugjar

---

# ====================================== P R O D U C T I O N ===========================================================

spring:
  profiles: local
db:
  source: mongo
  mongo:
    host: localhost
    database: slugjar
    login: slugjar
    password: slugjar
    authDb: admin