/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rmanders' at '1/30/17 9:25 PM' with Gradle 2.3
 *
 * @author rmanders, @date 1/30/17 9:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
